window.SEQUENCE_HUNTER_QUESTIONS = [
  {
    levelId: "3-1-L1-Q1",
    levelName: "數字排隊",
    unitName: "數列概念",
    questionType: "singleChoice",
    sourceType: "warmup",
    question: "下列哪一個最像數列的概念？",
    choices: ["一串依序排列的數字", "隨便寫在紙上的數字", "只有一個數字", "沒有順序的圖案"],
    answer: "A",
    hints: ["數列重點是「依序排列」。", "項就是數列中的每一個數。", "先找出哪個選項有順序。"],
    rescue: ["先不要看數字大小，只看它有沒有「排成一串」。", "把四個選項逐一問自己：這是不是一串有順序的東西？", "如果還不確定，先回到課本數列定義，或請老師協助判斷關鍵字。"],
    worksheetHint: "在學習單寫下你自己的生活數列例子。",
    difficulty: "easy",
    gameMode: "warmup",
    exp: 10
  },
  {
    levelId: "3-1-L1-Q2",
    levelName: "規則偵查",
    unitName: "數列概念",
    questionType: "shortAnswer",
    sourceType: "example",
    question: "若數列的一般項是 2n+1，請寫出前 5 項。",
    answer: "3,5,7,9,11",
    aliases: ["3 5 7 9 11", "3，5，7，9，11"],
    hints: ["把 n 分別換成 1,2,3,4,5。", "n 代表第幾項，不是答案本身。", "先算第 1 項，再算第 2 項。"],
    rescue: ["在學習單畫 5 格，格子上方寫 n=1、2、3、4、5。", "每一格都把 n 換成格子上方的數字，例如 n=1 時算 2×1+1。", "五格都算完後，把答案用逗號隔開輸入。"],
    worksheetHint: "在學習單逐格寫 n=1 到 n=5。",
    difficulty: "easy",
    gameMode: "main",
    exp: 20
  },
  {
    levelId: "3-1-L1-Q3",
    levelName: "規則偵查",
    unitName: "數列概念",
    questionType: "shortAnswer",
    sourceType: "practice",
    question: "把 n=1,2,3,4,5 代入一般項 n^2，請寫出得到的前 5 項。",
    answer: "1,4,9,16,25",
    aliases: ["1 4 9 16 25", "1，4，9，16，25"],
    hints: ["平方就是自己乘自己。", "n^2 表示 n 的平方。", "把 1,2,3,4,5 分別平方。"],
    rescue: ["在學習單畫 5 格，分別寫 n=1,2,3,4,5。", "每一格都做一次平方：1×1、2×2、3×3、4×4、5×5。", "把算出的 5 個數用逗號隔開，再輸入答案。"],
    worksheetHint: "在學習單寫出每一步代入。",
    difficulty: "easy",
    gameMode: "practice",
    exp: 20
  },
  {
    levelId: "3-1-L2-Q1",
    levelName: "加法密碼",
    unitName: "級數概念",
    questionType: "singleChoice",
    sourceType: "warmup",
    question: "「級數」最接近下列哪一個意思？",
    choices: ["把數列各項加起來", "把數列重新排序", "只看第一項", "只看最大值"],
    answer: "A",
    hints: ["級數是數列各項相加。", "級數通常會出現加號或加總符號。", "看到級數時先想「加起來」。"],
    rescue: ["先看四個選項中哪一個有「加起來」的意思。", "數列是排隊，級數是把排隊的數字加總。", "如果還分不清，先在學習單寫：數列=排隊，級數=相加。"],
    worksheetHint: "在學習單寫下「數列」和「級數」的差異。",
    difficulty: "easy",
    gameMode: "warmup",
    exp: 10
  },
  {
    levelId: "3-1-L2-Q2",
    levelName: "展開卷軸",
    unitName: "級數概念",
    questionType: "shortAnswer",
    sourceType: "example",
    question: "請把「k 從 1 到 5，每次代入 k 後相加」寫成加法式。答案格式例：1+2+3。",
    answer: "1+2+3+4+5",
    aliases: ["1 + 2 + 3 + 4 + 5"],
    hints: ["下限是 1，上限是 5。", "k 會依序變成 1,2,3,4,5。", "把每一次 k 的值寫出來並用加號連接。"],
    rescue: ["先不要急著算，把 k 的值排出來：1、2、3、4、5。", "題目說每一項都是 k，所以每一項就是 1、2、3、4、5。", "最後只要用加號連起來，格式像這樣：1+2+3。"],
    worksheetHint: "在學習單圈出下限與上限。",
    difficulty: "medium",
    gameMode: "main",
    exp: 20
  },
  {
    levelId: "3-1-L2-Q3",
    levelName: "展開卷軸",
    unitName: "級數概念",
    questionType: "shortAnswer",
    sourceType: "practice",
    question: "請將 i=1 到 4 的 3i+1 逐項展開。",
    answer: "4+7+10+13",
    aliases: ["4 + 7 + 10 + 13"],
    hints: ["把 i 分別代入 1,2,3,4。", "3i+1 是每一項的規則。", "先算每一項，再用加號連起來。"],
    rescue: ["在學習單畫 4 格，分別寫 i=1、i=2、i=3、i=4。", "每一格都代入 3i+1，例如 i=1 時是 3×1+1。", "四格都算完後，再用加號連成一串。"],
    worksheetHint: "學習單先寫 i=1,2,3,4 四列。",
    difficulty: "medium",
    gameMode: "practice",
    exp: 20
  },
  {
    levelId: "3-1-L3-Q1",
    levelName: "公差追蹤",
    unitName: "等差數列",
    questionType: "singleChoice",
    sourceType: "warmup",
    question: "數列 5,7,9,11 的公差是多少？",
    choices: ["2", "5", "7", "11"],
    answer: "A",
    hints: ["公差是後項減前項。", "d 代表公差。", "用第二項減第一項。"],
    rescue: ["先在學習單寫出 7-5。", "再寫出 9-7、11-9，看看每次差多少。", "如果每次差一樣，那個固定的差就是公差。"],
    worksheetHint: "學習單寫出 7-5。",
    difficulty: "easy",
    gameMode: "warmup",
    exp: 10
  },
  {
    levelId: "3-1-L3-Q2",
    levelName: "第 n 項定位",
    unitName: "等差數列",
    questionType: "shortAnswer",
    sourceType: "example",
    question: "已知等差數列首項為 5，公差為 2，求第 10 項。",
    answer: "23",
    hints: ["使用 an=a1+(n-1)d。", "a1=5，d=2，n=10。", "先填 a1、d、n，再代入公式。"],
    rescue: ["先在學習單寫三格：a1=5、d=2、n=10。", "把公式改寫成：第10項 = 5 + (10-1)×2。", "先算括號，再算乘法，最後輸入得到的數字。"],
    worksheetHint: "學習單分三格寫 a1、d、n。",
    difficulty: "medium",
    gameMode: "main",
    exp: 20
  },
  {
    levelId: "3-1-L3-Q3",
    levelName: "第 n 項定位",
    unitName: "等差數列",
    questionType: "shortAnswer",
    sourceType: "practice",
    question: "已知等差數列首項為 4，公差為 -3，求第 12 項。",
    answer: "-29",
    hints: ["使用 an=a1+(n-1)d。", "a1=4，d=-3，n=12。", "注意公差是負數。"],
    rescue: ["先在學習單寫三格：a1=4、d=-3、n=12。", "把公式改寫成：第12項 = 4 + (12-1)×(-3)。", "注意負號不要漏掉，算完後只輸入一個數字。"],
    worksheetHint: "學習單保留 4+(12-1)(-3) 的過程。",
    difficulty: "medium",
    gameMode: "practice",
    exp: 20
  },
  {
    levelId: "3-1-L3-Q4",
    levelName: "反推線索",
    unitName: "等差數列",
    questionType: "shortAnswer",
    sourceType: "example",
    question: "已知等差數列第 4 項為 15，第 7 項為 3，求首項。",
    answer: "27",
    hints: ["兩項相差 3 個公差。", "a4=15，a7=3。", "先用 a7-a4 求 3 個公差。"],
    rescue: ["先寫：a7-a4 = 3-15 = -12。", "第 4 項到第 7 項相差 3 個公差，所以 3d = -12。", "先求出 d，再從第 4 項往回推 3 步，算出首項。若還卡住，請帶著學習單問老師。"],
    worksheetHint: "學習單寫出 3-15=3d。",
    difficulty: "hard",
    gameMode: "challenge",
    exp: 25
  },
  {
    levelId: "3-1-L4-Q1",
    levelName: "空格橋梁",
    unitName: "等差數列",
    questionType: "shortAnswer",
    sourceType: "example",
    question: "在 4 與 -24 之間插入 6 個數，使其成等差數列，求插入的第 3 個數。",
    answer: "-8",
    hints: ["插入 6 個數後共有 8 項。", "4 是第 1 項，-24 是第 8 項。", "先求公差，再找插入第 3 個數對應原數列第幾項。"],
    rescue: ["先畫 8 格：第1格是 4，第8格是 -24。", "從第1項到第8項相差 7 個公差，所以用 -24-4 算出 7d。", "插入的第 3 個數是整個數列的第 4 項，先求 d 再回來算第 4 項。"],
    worksheetHint: "學習單畫出 8 個空格。",
    difficulty: "hard",
    gameMode: "main",
    exp: 20
  },
  {
    levelId: "3-1-L4-Q2",
    levelName: "火柴工坊",
    unitName: "等差數列應用",
    questionType: "shortAnswer",
    sourceType: "example",
    question: "用 4 根火柴排 1 個正方形，7 根排 2 個正方形，依此規則排 15 個正方形需要幾根？",
    answer: "46",
    hints: ["每多一個正方形多 3 根。", "a1=4，d=3，n=15。", "先列出 4,7,10 找規則。"],
    rescue: ["先列出前 3 項：1 個正方形 4 根，2 個 7 根，3 個 10 根。", "觀察每次都多 3 根，所以這是公差 d=3。", "把 n=15 代入等差公式，或從 4 開始加 14 次的 3。"],
    worksheetHint: "學習單畫前 3 個正方形或寫前三項。",
    difficulty: "medium",
    gameMode: "application",
    exp: 20
  },
  {
    levelId: "3-1-L4-Q3",
    levelName: "馬拉松試煉",
    unitName: "等差數列應用",
    questionType: "singleChoice",
    sourceType: "boss",
    question: "第一週跑 8 公里，每週比前一週增加 3 公里，最快第幾週該週訓練長度會超過 42.195 公里？",
    choices: ["12", "13", "14", "15"],
    answer: "B",
    hints: ["使用 an=a1+(n-1)d，並找出超過目標的最小 n。", "a1=8，d=3，目標是超過 42.195。", "試算選項，找第一個超過的週數。"],
    rescue: ["先圈出題目的三個數字：第一週 8 公里、每週增加 3 公里、目標 42.195 公里。", "把選項 12、13、14、15 分別代入 8+(n-1)×3。", "找第一個算出來大於 42.195 的選項；如果還卡住，先記下你試算到哪裡再問老師。"],
    worksheetHint: "學習單圈出「超過」兩字，注意不是等於。",
    difficulty: "hard",
    gameMode: "boss",
    exp: 40
  },
  {
    levelId: "3-1-L5-Q1",
    levelName: "Sigma 入門",
    unitName: "Σ 符號",
    questionType: "singleChoice",
    sourceType: "warmup",
    question: "符號 Σ 在級數中主要表示什麼意思？",
    choices: ["把許多項加起來", "把所有數相乘", "只取第一項", "只看最大值"],
    answer: "A",
    hints: ["Σ 讀作 sigma。", "英文 summation 有總和的意思。", "看到 Σ，先想到把指定範圍的項目相加。"],
    rescue: ["Σ 不是乘法符號。", "它是在提醒你：從下限到上限，把每一項代入後加起來。", "所以最接近的選項是把許多項加起來。"],
    worksheetHint: "在學習單圈出 Σ，旁邊寫上「總和」。",
    difficulty: "easy",
    gameMode: "warmup",
    exp: 10
  },
  {
    levelId: "3-1-L5-Q2",
    levelName: "上下限偵查",
    unitName: "Σ 符號",
    questionType: "singleChoice",
    sourceType: "warmup",
    question: "Σ 從 k=1 到 5，代表 k 要依序代入哪些數？",
    choices: ["1,2,3,4,5", "0,1,2,3,4", "5,6,7,8,9", "只有 1 和 5"],
    answer: "A",
    hints: ["下限是起點，上限是終點。", "k=1 到 5，要把中間的整數都列出來。", "不要只寫頭尾，還要包含 2,3,4。"],
    rescue: ["先寫起點 1。", "再一路數到終點 5。", "所以 k 會代入 1,2,3,4,5。"],
    worksheetHint: "在學習單先寫 k=1,2,3,4,5。",
    difficulty: "easy",
    gameMode: "warmup",
    exp: 10
  },
  {
    levelId: "3-1-L5-Q3",
    levelName: "逐項展開",
    unitName: "Σ 符號",
    questionType: "shortAnswer",
    sourceType: "example",
    question: "請將 Σ k（k=1 到 5）逐項展開。",
    answer: "1+2+3+4+5",
    aliases: ["1 + 2 + 3 + 4 + 5", "1,2,3,4,5"],
    hints: ["k 從 1 開始。", "每次把 k 換成下一個整數。", "最後用加號把 1 到 5 接起來。"],
    rescue: ["先列 k=1,2,3,4,5。", "因為一般項是 k，所以代入後就是 1,2,3,4,5。", "級數要用加號連起來：1+2+3+4+5。"],
    worksheetHint: "在學習單先寫上下限，再逐項代入。",
    difficulty: "medium",
    gameMode: "main",
    exp: 20
  },
  {
    levelId: "3-1-L5-Q4",
    levelName: "代入展開",
    unitName: "Σ 符號",
    questionType: "shortAnswer",
    sourceType: "practice",
    question: "請將 Σ(3i+1)（i=1 到 5）逐項展開。",
    answer: "4+7+10+13+16",
    aliases: ["4 + 7 + 10 + 13 + 16", "4,7,10,13,16"],
    hints: ["i 要代入 1,2,3,4,5。", "先算 3×1+1。", "每一項算完後，用加號連接。"],
    rescue: ["i=1 時，3×1+1=4。", "i=2 時，3×2+1=7。", "依序算到 i=5，得到 4,7,10,13,16。"],
    worksheetHint: "在學習單畫 5 格，分別代入 i=1 到 5。",
    difficulty: "medium",
    gameMode: "practice",
    exp: 20
  },
  {
    levelId: "3-1-L5-Q5",
    levelName: "常數級數",
    unitName: "Σ 符號",
    questionType: "shortAnswer",
    sourceType: "practice",
    question: "請計算 Σ 3（n=1 到 6）的值。",
    answer: "18",
    aliases: ["3+3+3+3+3+3"],
    hints: ["這裡每一項都是 3。", "n=1 到 6，共有 6 項。", "所以是 6 個 3 相加。"],
    rescue: ["先不要被 n 嚇到，式子裡只有常數 3。", "n=1 到 6，共 6 項。", "3+3+3+3+3+3=18。"],
    worksheetHint: "在學習單寫出 6 個 3，再相加。",
    difficulty: "medium",
    gameMode: "practice",
    exp: 20
  },
  {
    levelId: "3-1-L5-Q6",
    levelName: "無窮符號",
    unitName: "Σ 符號",
    questionType: "singleChoice",
    sourceType: "practice",
    question: "Σ 的上限若是 ∞，代表這個級數有什麼特徵？",
    choices: ["有無窮多項", "只有一項", "一定等於 0", "不能展開"],
    answer: "A",
    hints: ["∞ 讀作無限大。", "上限是 ∞，代表不會在某個有限數停下來。", "所以項數不是 5 項、10 項，而是無窮多項。"],
    rescue: ["有限級數會有明確上限，例如 5 或 20。", "無窮級數的上限是 ∞。", "因此它表示有無窮多項。"],
    worksheetHint: "在學習單把 ∞ 圈起來，旁邊寫「無窮多項」。",
    difficulty: "easy",
    gameMode: "practice",
    exp: 10
  },
  {
    levelId: "3-1-L6-Q1",
    levelName: "拆開性質",
    unitName: "Σ 的運算",
    questionType: "singleChoice",
    sourceType: "warmup",
    question: "Σ(a_k+b_k) 可以改寫成哪一個？",
    choices: ["Σa_k+Σb_k", "Σa_k×Σb_k", "a_k+b_k", "Σ(a_k×b_k)"],
    answer: "A",
    hints: ["加法可以分成兩堆來加。", "Σ(a_k+b_k) 是每一項裡有 a_k 和 b_k。", "可以拆成 a_k 的總和加 b_k 的總和。"],
    rescue: ["先想成 (a1+b1)+(a2+b2)+...。", "把 a 的項目排一堆，b 的項目排一堆。", "所以會變成 Σa_k+Σb_k。"],
    worksheetHint: "在學習單把 a 的部分與 b 的部分用不同顏色圈起來。",
    difficulty: "medium",
    gameMode: "main",
    exp: 20
  },
  {
    levelId: "3-1-L6-Q2",
    levelName: "性質代入",
    unitName: "Σ 的運算",
    questionType: "shortAnswer",
    sourceType: "example",
    question: "已知 Σa_k=15，Σb_k=23，求 Σ(3a_k+b_k) 的值。",
    answer: "68",
    hints: ["先把 Σ(3a_k+b_k) 拆開。", "Σ3a_k 可以寫成 3Σa_k。", "再代入 15 和 23。"],
    rescue: ["Σ(3a_k+b_k)=3Σa_k+Σb_k。", "代入 Σa_k=15，Σb_k=23。", "3×15+23=45+23=68。"],
    worksheetHint: "先寫拆開式，再代入已知數字。",
    difficulty: "hard",
    gameMode: "challenge",
    exp: 25
  },
  {
    levelId: "3-1-L6-Q3",
    levelName: "常數補給",
    unitName: "Σ 的運算",
    questionType: "shortAnswer",
    sourceType: "practice",
    question: "已知 Σa_k=15，Σb_k=23，且 k=1 到 10，求 Σ(2a_k-b_k+1) 的值。",
    answer: "17",
    hints: ["先拆成 2Σa_k - Σb_k + Σ1。", "k=1 到 10，所以 Σ1 有 10 個 1。", "最後代入 15 和 23。"],
    rescue: ["Σ(2a_k-b_k+1)=2Σa_k-Σb_k+Σ1。", "Σ1=10，因為從 1 到 10 有 10 項。", "2×15-23+10=30-23+10=17。"],
    worksheetHint: "別忘了 +1 也要加 10 次。",
    difficulty: "hard",
    gameMode: "boss",
    exp: 30
  }
];
